invoice/urls.py
from django.conf.urls import url
from . import views

app_name = 'invoicemanager'

urlpatterns = [

    url(r'^$', views.invoices.index, name='index'),

    # INVOICES
    url(r'^invoice/new/$', views.invoices.new_invoice, name='new_invoice'),
    url(r'^invoice/all/$', views.invoices.all_invoices, name='all_invoices'),
    url(r'^invoice/draft/$', views.invoices.draft_invoices, name='draft_invoices'),
    url(r'^invoices/invalid/$', views.invoices.invalid_invoices, name='invalid_invoices'),
    url(r'^invoice/paid/$', views.invoices.paid_invoices, name='paid_invoices'),
    url(r'^invoice/unpaid/$', views.invoices.unpaid_invoices, name='unpaid_invoices'),
    url(r'^invoice/(?P<invoice_id>[0-9]+)/$', views.invoices.invoice, name='invoice'),
    url(r'^invoice/search/$', views.invoices.search_invoice, name='search_invoice'),
    url(r'^view-invoice/(?P<invoice_id>[0-9]+)/$', views.invoices.view_invoice, name='view_invoice'),
    url(r'^invoice/(?P<invoice_id>[0-9]+)/print/$', views.invoices.print_invoice, name='print_invoice'),
    url(r'^invoice/(?P<invoice_id>[0-9]+)/invalidate/$', views.invoices.invalidate_invoice, name='invalidate_invoice'),

    # ITEMS
    url(r'^invoice/(?P<invoice_id>[0-9]+)/item/add/$', views.items.add_item, name='add_item'),
    url(r'^invoice/(?P<invoice_id>[0-9]+)/item/(?P<invoiceitem_id>[0-9]+)/delete/$', views.items.delete_item, name='delete_item'),

    # CUSTOMERS
    url(r'^customers/$', views.customers.customer_list, name='customer_list'),
    url(r'^customer/(?P<customer_id>[0-9]+)/$', views.customers.customer, name='customer'),
    url(r'^customer/(?P<customer_id>[0-9]+)/update/$', views.customers.update_customer, name='update_customer'),
    url(r'^customer/(?P<customer_id>[0-9]+)/delete/$', views.customers.delete_customer, name='delete_customer'),
    url(r'^customer/new/$', views.customers.new_customer, name='new_customer'),
]

invoice/models/invoice_item.py
from django.db import models

from invoice.models.inv import Invoice


class InvoiceItem(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    description = models.TextField()
    cost = models.DecimalField(decimal_places=2, max_digits=10)
    qty = models.IntegerField()

    def __str__(self):
        return self.name

    def total(self):
        return self.cost * self.qty

invoice/forms.py
from __future__ import unicode_literals

from django import forms
from django.forms import formset_factory
from .models.customer import Customer


class CustomerForm(forms.ModelForm):
    """
        Forms for creating a new customer.
    """
    class Meta:
        model = Customer
        fields = ['name', 'address', 'city', 'region', 'country', 'email', ]
        widgets = {'name': forms.TextInput(attrs={"class": "form-control"}),
                   'address': forms.TextInput(attrs={"class": "form-control"}),
                   'city': forms.TextInput(attrs={"class": "form-control"}),
                   'region': forms.TextInput(attrs={"class": "form-control"}),
                   'country': forms.TextInput(attrs={"class": "form-control"}),
                   'email': forms.TextInput(attrs={"class": "form-control"}),
                   }


class ItemForms(forms.Form):
    item = forms.CharField(min_length=2, max_length=100, widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    description = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    cost = forms.DecimalField(
        widget=forms.TextInput(
            attrs={'placeholder': '0.00', 'class': 'form-control' }))
    qty = forms.IntegerField(min_value=1)


ItemFormset = formset_factory(ItemForms, extra=1, min_num=0, max_num=100)

invoice/views/_init_.py
from invoices import *
from items import *
from customers import *

invoice/views/admin.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
import datetime


# Administrative settings
def users(request):
    return None


def settings(request):
    return None

invoice/views/customers.py
# Third Party imports
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse

# Local Applications imports
from invoice.models.customer import Customer
from invoice.models.inv import Invoice
from invoice.forms import CustomerForm


@login_required(login_url='users:login')
def customer_list(request):
    """List all Customers

    List all customers and paginate them to display 25
    customers per page.

    """
    customer = Customer.objects.all()
    page = request.GET.get('page', 1)

    paginator = Paginator(customer, 25)
    try:
        customers = paginator.page(page)
    except PageNotAnInteger:
        customers = paginator.page(1)
    except EmptyPage:
        customers = paginator.page(paginator.num_pages)
    context = {
        'title': 'Customer List',
        'customers': customers,
    }
    return render(request, 'invoice/customers.html', context)


@login_required(login_url='users:login')
def customer(request, customer_id):
    """
      Displays the details for a particular customer with their
      invocies.

    """
    customer = get_object_or_404(Customer, pk=customer_id)
    invoices = Invoice.objects.filter(customer=customer).order_by('-date_created')
    context = {
        'title': "Customer info - %s" % customer.name,
        'customer': customer,
        'invoices': invoices,
    }
    return render(request, 'invoice/customer.html', context)


# View for creating a new customer.
@login_required(login_url='users:login')
def new_customer(request):
    if request.method == 'POST':
        form = CustomerForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'New Customer created successfully')
            return redirect('invoice:customer_list')
    else:
        form = CustomerForm()

    context = {'form': form}
    template_name = 'invoice/new_customer.html'

    return render(request, template_name, context)


# Update customer
@login_required(login_url='users:login')
def update_customer(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    if request.method == 'POST':
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            form.save()
            messages.success(request, 'Customer details updated successfully')
            return HttpResponseRedirect(reverse('invoice:customer',
                                                args=(customer.id,)))
    else:
        form = CustomerForm(instance=customer)
    context = {
        'form': form,
    }
    template_name = 'invoice/customer.html'
    return render(request, template_name, context)


# Delete customer
@login_required(login_url='users:login')
def delete_customer(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    customer.delete()
    messages.success(request, "Customer successfully deleted.")
    return HttpResponseRedirect(reverse('invoice:customer_list'))

invoice/views/invoices.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import datetime

from ..forms import ItemFormset


# Default invoice list, show recent invoices by the date it was created.
from invoice.models.customer import Customer
from invoice.models.inv import Invoice


@login_required(login_url='users:login')
def index(request):
    invoice = Invoice.objects.all().order_by('-date_created')
    page = request.GET.get('page', 1)

    paginator = Paginator(invoice, 25)
    try:
        invoices = paginator.page(page)
    except PageNotAnInteger:
        invoices = paginator.page(1)
    except EmptyPage:
        invoices = paginator.page(paginator.num_pages)
    context = {
        'title': 'Recent Invoices',
        'invoice_list': invoices,
    }
    return render(request, 'invoice/index.html', context)


# Show big list of all invoices
@login_required(login_url='users:login')
def all_invoices(request):
    invoice = Invoice.objects.order_by('-date_created')
    page = request.GET.get('page', 1)

    paginator = Paginator(invoice, 25)
    try:
        invoices = paginator.page(page)
    except PageNotAnInteger:
        invoices = paginator.page(1)
    except EmptyPage:
        invoices = paginator.page(paginator.num_pages)
    context = {
        'title': 'All Invoices',
        'invoice_list': invoices,
    }
    return render(request, 'invoice/all_invoice.html', context)


# Show draft invoices
@login_required(login_url='users:login')
def draft_invoices(request):
    invoice = Invoice.objects.filter(status='Draft').order_by('-date_created')
    page = request.GET.get('page', 1)

    paginator = Paginator(invoice, 25)
    try:
        invoices = paginator.page(page)
    except PageNotAnInteger:
        invoices = paginator.page(1)
    except EmptyPage:
        invoices = paginator.page(paginator.num_pages)
    context = {
        'title': 'Draft Invoices',
        'invoice_list': invoices,
    }
    return render(request, 'invoice/index.html', context)


# Show invalid invoices
@login_required(login_url='users:login')
def invalid_invoices(request):
    invoice = Invoice.objects.filter(valid='False').order_by('-date_created')
    page = request.GET.get('page', 1)

    paginator = Paginator(invoice, 25)
    try:
        invoices = paginator.page(page)
    except PageNotAnInteger:
        invoices = paginator.page(1)
    except EmptyPage:
        invoices = paginator.page(paginator.num_pages)
    context = {
        'title': 'Invalid Invoices',
        'invoice_list': invoices,
    }
    return render(request, 'invoice/invalid_invoices.html', context)


# Show paid invoices
@login_required(login_url='users:login')
def paid_invoices(request):
    invoice = Invoice.objects.filter(status='Paid').order_by('-date_created')
    page = request.GET.get('page', 1)

    paginator = Paginator(invoice, 25)
    try:
        invoices = paginator.page(page)
    except PageNotAnInteger:
        invoices = paginator.page(1)
    except EmptyPage:
        invoices = paginator.page(paginator.num_pages)
    context = {
        'title': 'Paid Invoices',
        'invoice_list': invoices,
    }
    return render(request, 'invoice/index.html', context)


# Show unpaid invoices
@login_required(login_url='users:login')
def unpaid_invoices(request):
    invoice = Invoice.objects.filter(status='Unpaid').order_by('-date_created')
    page = request.GET.get('page', 1)

    paginator = Paginator(invoice, 25)
    try:
        invoices = paginator.page(page)
    except PageNotAnInteger:
        invoices = paginator.page(1)
    except EmptyPage:
        invoices = paginator.page(paginator.num_pages)
    context = {
        'title': 'Unpaid Invoices',
        'invoice_list': invoices,
    }
    return render(request, 'invoice/index.html', context)


# Display a specific invoice
@login_required(login_url='users:login')
def invoice(request, invoice_id):
    invoice = get_object_or_404(Invoice, pk=invoice_id)

    itemformset = ItemFormset()
    context = {
        'title': 'Invoice ' + invoice_id,
        'invoice': invoice,
        'formset': itemformset, 
    }
    return render(request, 'invoice/invoice.html', context)


# Search for invoice
@login_required(login_url='users:login')
def search_invoice(request):
    id = request.POST['id']
    return HttpResponseRedirect(reverse('invoice:view_invoice', args=(id,)))


# Create new invoice
@login_required(login_url='users:login')
def new_invoice(request):
        # If no customer_id is defined, create a new invoice
    if request.method == 'POST':
        customer_id = request.POST.get("customer_id", "None")
        expiration_date = request.POST.get("expiration_date", datetime.date.today())
        status = request.POST.get("status", 'Unpaid')

        if customer_id == 'None':
            customers = Customer.objects.order_by('name')
            context = {
                'title': 'New Invoice',
                'customer_list': customers,
                'error_message': 'Please select a customer.',
            }
            return render(request, 'invoice/new_invoice.html', context)
        else:
            customer = get_object_or_404(Customer, pk=customer_id)
            i = Invoice(customer=customer,
                        expiration_date=expiration_date, status=status)
            i.save()
            return HttpResponseRedirect(reverse('invoice:invoice', args=(i.id,)))

    else:
        # Customer list needed to populate select field
        customers = Customer.objects.order_by('name')
        context = {
            'title': 'New Invoice',
            'customer_list': customers,
        }
        return render(request, 'invoice/new_invoice.html', context)


# View invoice
@login_required(login_url='users:login')
def view_invoice(request, invoice_id):
    invoice = get_object_or_404(Invoice, pk=invoice_id)
    context = {
        'title': "Invoice " + invoice_id,
        'invoice': invoice,
    }
    return render(request, 'invoice/view_invoice.html', context)


# Print invoice
@login_required(login_url='users:login')
def print_invoice(request, invoice_id):
    invoice = get_object_or_404(Invoice, pk=invoice_id)
    context = {
        'title': "Invoice " + invoice_id,
        'invoice': invoice,
    }
    return render(request, 'invoice/print_invoice.html', context)


# Invalidate an invoice
@login_required(login_url='users:login')
def invalidate_invoice(request, invoice_id):
    invoice = get_object_or_404(Invoice, pk=invoice_id)
    invoice.valid = False
    invoice.save()
    return HttpResponseRedirect(reverse('invoice:index'))

invoice/views/items.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from ..forms import ItemFormset

# Add invoiceitem to invoice
from invoice.models.inv import Invoice
from invoice.models.invoice_item import InvoiceItem
from invoice.models.customer import Customer


@login_required(login_url='users:login')
def add_item(request, invoice_id):
	invoice = get_object_or_404(Invoice, pk=invoice_id)
	items_added, items_not_add = (0, 0)
	
	try:
		if request.method == 'POST':
			itemformset = ItemFormset(request.POST)
			
			if itemformset.is_valid():
				for form in itemformset:
					
					item_name = form.cleaned_data.get('item')
					item_description = form.cleaned_data.get('description')
					item_cost = form.cleaned_data.get('cost')
					item_qty = form.cleaned_data.get('qty')

					if item_name is None or item_cost is None or item_qty is None:
						items_not_add += 1
					else:
						invoice_obj = invoice.invoiceitem_set.create(name=item_name, description=item_description, cost=item_cost, qty=item_qty)
						invoice_obj.save()
						items_added += 1
						del invoice_obj
				
				if items_added > 0:
					messages.success(request, '%d items added successfully to invoice !' % items_added)
				
				if items_not_add > 0:
					messages.warning(request, "%d items have been discarded since some fields were empty." % items_not_add)
					
			else:
				messages.warning(request, "Form not valid. Most form fields were empty")
				#if form is invalid re-render the invoice
				return render(request, 'invoice/invoice.html', {
        					'title': 'Invoice ' + invoice_id,
        					'invoice': invoice,
        					'formset': itemformset, 
    					})

	except (KeyError, Invoice.DoesNotExist):
		return render(request, 'invoice/view_invoice.html', {
			'invoice': invoice,
			'error_message': 'Not all fields were completed.',
		})
	else:
		return HttpResponseRedirect(reverse('invoice:invoice', args=(invoice.id,)))



# Delete invoiceitem from invoice
@login_required(login_url='users:login')
def delete_item(request, invoiceitem_id, invoice_id):

    item = get_object_or_404(InvoiceItem, pk=invoiceitem_id)
    invoice = get_object_or_404(Invoice, pk=invoice_id)
    try:
        item.delete()
        messages.warning(request, 'Item deleted successfully from invoice! ')
    except (KeyError, InvoiceItem.DoesNotExist):
        return render(request, 'invoice/view_invoice.html', {
            'invoice': invoice,
            'error_message': 'Item does not exist.',
        })
    else:
        return HttpResponseRedirect(reverse('invoice:invoice', args=(invoice.id,)))

invoice/templates/invoice/invoice.html
{% extends 'base.html' %}

{% block content %}

{% if error_message %}

<div class="alert alert-danger">{{ error_message }}</div>

{% endif %}

{% if invoice %}
<!-- Display invoice -->

<h2 class="text-center">Invoice {{ invoice.id }}</h2>

<!-- Customer information -->
<form method="POST" action="{% url 'invoice:view_invoice' invoice.id %}" name="customer" class="form-horizontal">
	{% csrf_token %}
	<div class="panel panel-primary">
		<div class="panel-heading">Customer</div>
		<div class="panel-body">
			<div class="form-group">
				<label class="col-sm-3 control-label">Customer:</label>
				<div class="col-sm-6">
					<p class="form-control-static"><a href="{% url 'invoice:customer' invoice.customer.id %}">{{ invoice.customer }}</a></p>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-3 control-label">Expiration Date:</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" name="expiration_date" id="expirationdate" value="{{ invoice.expiration_date|date:"SHORT_DATE_FORMAT" }}">
				</div>
				<script type="text/javascript">
					$(function () {
						$('#expirationdate').datepicker({
							todayBtn: "linked",
							orientation: "bottom left",
							autoclose: true
						});
					});
					</script>
			</div>
			<div class="form-group">
				<label class="col-sm-3 control-label">Status:</label>
				<div class="col-sm-6">
					<select name="status" class="form-control">
						<option value="Draft" {% if invoice.draft %}selected{% endif %}>Draft</option>
						<option value="Paid" {% if invoice.paid %}selected{% endif %}>Paid</option>
						<option value="Unpaid" {% if invoice.unpaid %}selected{% endif %}>Unpaid</option>
					<select>
				</div>
			</div>
		</div>
		<div class="panel-footer">
			<input type="submit" value="Save" class="btn btn-primary">
			<a href="{% url 'invoice:print_invoice' invoice.id %}" target="_new" class="btn btn-default">Printable Invoice</a>
		</div>
	</div>
</form>

<!-- END Customer information -->

<!-- Invoice items -->

<form action="{% url 'invoice:add_item' invoice.id %}" method="post" class="form-inline">
	{% csrf_token %}
	{{ formset.management_form }}
	
	<div class="panel panel-primary">
		<div class="panel-heading">Invoice items</div>
		<table class="table table-hover">
			<tr>
				<th>Item</th>
				<th>Description</th>
				<th>Cost (GHS)</th>
				<th>Qty</th>
				<th>Total (GHS)</th>
				<th class="text-right">Actions</th>
			</tr>
			{% for item in invoice.invoiceitem_set.all %}
			<tr>
				<td>{{ item.name }}</td>
				<td>{{ item.description }}</td>
				<td>GHS {{ item.cost }}</td>
				<td>{{ item.qty }}</td>
				<td>{{ item.total }}</td>
				<td class="text-right">
					<button type="button" id="delete-btn" class="btn btn-xs btn-danger" data-toggle="modal" data-target="#confirmdelete" data-object-name="{{ item.name }}" data-delete-url="{% url 'invoicemanager:delete_item' invoice.id item.id %}">Delete</button>
				</td>
			</tr>
			{% endfor %}
			
			{% for forms in formset %}
			<tr class="form-row">	
				<td id="items-field">{{ forms.item }}</td>
				<td id="description-field">{{ forms.description }}</td>
				<td>
					<div class="input-group" id="cost-field">
						<span class="input-group-addon"></span>{{ forms.cost }}
					</div>
				</td>
				<td id="qty-field">{{ forms.qty }}</td>
				<td>&nbsp;</td>
				<td>
					<div class="btn-group" role="group">
						<button class="btn btn-primary add-form-row">+</button>
						<button class="btn btn-danger remove-form-row">-</button>
					</div>
				</td>
				
			</tr>
			{% endfor %}
				
		</table>
		<div class="panel-footer">
			<input type="submit" class="btn btn-primary" value="Add">
			<div id="total-output" class="text-right"><strong>Total: GHS {{ invoice.total_items }}</strong></div>
		</div>
	</div>
</form>

<div class="well text-right">Invoice net total: GHS {{ invoice.total }}</div>


<!-- Delete confirmation modal -->
<div class="modal fade" id="confirmdelete" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">Confirm</h4>
			</div>
			<div class="modal-body">

			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">No</button>
				<a href="#" class="btn btn-danger">Yes</a>
			</div>
		</div>
	</div>
</div>

<script>
	function isFormFieldsEmpty() {
		var test = true;
		$('table tr input').each(function() {
			var value = $(this).val();
			if (value) { test &=false; } 
		});
		return test;
	}

	function someFormFieldsEmpty(){
		var test = false;
		$('table tr input').each(function(){
			var value = $(this).val();
			if ( $.trim(value).length == 0 ) {
				test = true;
			}
		});
		return test;
	}

	$("div.panel-footer input[value=Add]").click(function(event){
		if ( someFormFieldsEmpty() ) {
			var response = confirm("Most fields are empty. They will be ignore if you continue with the operation. Do you want to continue?");
			if ( response == false ) { event.preventDefault(); }
		}
	});

	/*Automatically update the total cost of items in invoice when input fields are changed*/
	$("table tr input").change(function(event){
		var elementNameAttr = $(this).attr("name"), index, cost_value, qty_value, sum=0;
		if (elementNameAttr) { index = elementNameAttr.split("-")[1]; }
		
		cost_value = parseFloat( $("table tr input[name=form-"+index+"-cost]").val() );
		qty_value = parseInt( $("table tr input[name=form-"+index+"-qty]").val() );
		if (cost_value && qty_value) {  //if fields are set
			var fourth_td_element = $("table tr input[name=form-"+index+"-qty]").parent().siblings()[3];
			fourth_td_element.innerText = cost_value * qty_value;
			
			var i = 0;
			$("table tr").each(function() {  /*sum all total values*/
				fourth_td_element = $(this).children()[4];
				var value = fourth_td_element.innerText;
				if (value && $.trim(value).length != 0 && i > 0){ sum += parseFloat(value); }
				i += 1;
			});

			$("div#total-output").html("<strong>Total: GHS "+sum+"</strong>");
			$("div#total-output").attr("data", sum);
			$("div.well").text("Invoice net total: GHS "+sum);
		} else {
			var fourth_td_element = $("table tr input[name=form-"+index+"-qty]").parent().siblings()[3];
			fourth_td_element.innerText = 0;
		}
	});

	function on_minus_press(elem){
		var elem = $(elem).parent().parent().siblings()[4];
		var elem_value = parseFloat(elem.innerText);
		var totalElementData = $("div#total-output").attr("data");
		
		if ( totalElementData ){
			totalElementData = parseFloat(totalElementData);
			totalElementData -= elem_value;
			
			if ( totalElementData > 0 ) {
				$("div#total-output").html("<strong>Total: GHS "+totalElementData+"</strong>");
				$("div#total-output").attr("data", totalElementData);
				$("div.well").text("Invoice net total: GHS "+totalElementData);
			}
		}
	}

	$(document).ready(function() {
		$('#confirmdelete').on('show.bs.modal', function(e) {
		    var name = $(e.relatedTarget).data('object-name');
			var url = $(e.relatedTarget).data('delete-url');
			var confirm_msg;

			if ( isFormFieldsEmpty() ) { 
				confirm_msg = "Are you sure you want to delete " + name + "?";
			} else { 
				confirm_msg = "This operation will clear the data you have entered in the forms. Do you really want to continue?";
			}
			
			$('#confirmdelete .modal-body').text(confirm_msg);
			$('#confirmdelete .modal-footer a').attr('href', url);
		});
	});
</script>
<!-- END delete confirmation modal -->


<!---Handles the formset on this view-->
<script type="text/javascript">
	function updateElementIndex(el, prefix, ndx) {
		var id_regex = new RegExp('(' + prefix + '-\\d+)');
		var replacement = prefix + '-' + ndx;
		if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
		if (el.id) el.id = el.id.replace(id_regex, replacement);
		if (el.name) el.name = el.name.replace(id_regex, replacement);
	}
	
	function cloneMore(selector, prefix) {
		var newElement = $(selector).clone(true);
		var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
		newElement.find(':input').each(function() {
			var name = $(this).attr('name')
			if(name) {
				name = name.replace('-' + (total-1) + '-', '-' + total + '-');
				var id = 'id_' + name;
				$(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
			}
		});
		total++;
		$('#id_' + prefix + '-TOTAL_FORMS').val(total);
		$(selector).after(newElement);
		var conditionRow = $('.form-row:not(:last)');
		conditionRow.find('.btn.add-form-row')
		return false;
	}
	
	function deleteForm(prefix, btn) {
		var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
		if (total > 1){
			btn.closest('.form-row').remove();
			var forms = $('.form-row');
			$('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
			for (var i=0, formCount=forms.length; i<formCount; i++) {
				$(forms.get(i)).find(':input').each(function() {
					updateElementIndex(this, prefix, i);
				});
			}
		}
		return false;
	}
	$(document).on('click', '.add-form-row', function(e){
		e.preventDefault();
		cloneMore('.form-row:last', 'form');
		return false;
	});
	$(document).on('click', '.remove-form-row', function(e){
		e.preventDefault();
		on_minus_press($(this));
		deleteForm('form', $(this));
		return false;
	});
	
</script>
<!---Handles the formset on this view-->


{% if confirm_update %}
<!-- Update success modal -->
<div class="modal fade" id="updateconfirm" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-body">
			<h4>Changes saved!</h4>
        </div>
        <div class="modal-footer">
			<a href="#" data-dismiss="modal" class="btn btn-primary">Ok</a>
        </div>
      </div>
    </div>
</div>

<!-- Trigger success confirmation modal -->
<script>
$(document).ready(function(){
	$("#updateconfirm").modal();
});
</script>
<!-- End success confirmation modal -->
{% endif %}

<!-- End display invoice -->

{% else %}
<!-- Display invoice error -->

<div class="alert alert-warning">Invoice number not found!</div>

<!-- End display invoice error -->
{% endif %}

{% endblock %}

invoice/templates/invoice/new_invoice.html
{% extends 'base.html' %}

{% block content %}

{% if error_message %}
<div class="alert alert-danger">{{ error_message }}</div>
{% endif %}

{% if customer_list %}

<form method="POST" action="{% url 'invoice:new_invoice' %}" name="customer" class="form-horizontal">
	{% csrf_token %}
	<div class="panel panel-primary">
		<div class="panel-heading">Select Customer</div>
		<div class="panel-body">
			<div class="form-group">
				<label class="col-sm-3 control-label">Customer:</label>
				<div class="col-sm-6">
					<select class="form-control" name="customer_id">
						<option value="None">(Select)</option>
						{% for customer in customer_list %}
						<option value="{{ customer.id }}">{{ customer.name }}</option>
						{% endfor %}
					</select>
				</div>
			</div>
		</div>
		<div class="panel-footer">
			<a href="{% url 'invoice:new_customer' %}" class="btn btn-default">Add New Customer</a>
			<input type="submit" value="Create Invoice" class="btn btn-primary">
		</div>
	</div>
</form>

{% else %}

<div class="alert alert-danger">No customers!</div>

{% endif %}

{% endblock %}